### ISSUE TITLE
Site re-design breaks history scraping

### ISSUE THREAD

**Issue by xECK29x** [colinrsmall/ehm_roster_tools#4]
The new Eliteprospects redesign appears to have broken the career history scraper. Example errors (ran from any team/league):

Missing dob information: Nathan Airey
Missing player information for: https://www.eliteprospects.com/player/475182/nathan-airey
Traceback (most recent call last):
  File "<ipython-input-6-ef681e2b523b>", line 59, in scrape
    scrape_player_page(link, csvwriter)
  File "<ipython-input-5-ea5904e59983>", line 88, in scrape_player_page
    position = player_page.find('div', text=position_text).next_element.next_element.next_element.text.strip()
AttributeError: 'NoneType' object has no attribute 'next_element'
Missing dob information: Jay Thomson
Missing player information for: https://www.eliteprospects.com/player/391056/jay-thomson
Traceback (most recent call last):
  File "<ipython-input-6-ef681e2b523b>", line 59, in scrape
    scrape_player_page(link, csvwriter)
  File "<ipython-input-5-ea5904e59983>", line 88, in scrape_player_page
    position = player_page.find('div', text=position_text).next_element.next_element.next_element.text.strip()
AttributeError: 'NoneType' object has no attribute 'next_element'
Missing dob information: Quaid Anderson
Missing player information for: https://www.eliteprospects.com/player/477754/quaid-anderson
Traceback (most recent call last):
  File "<ipython-input-6-ef681e2b523b>", line 59, in scrape
    scrape_player_page(link, csvwriter)
  File "<ipython-input-5-ea5904e59983>", line 88, in scrape_player_page
    position = player_page.find('div', text=position_text).next_element.next_element.next_element.text.strip()
AttributeError: 'NoneType' object has no attribute 'next_element'
Missing dob information: Cole Assailly
Missing player information for: https://www.eliteprospects.com/player/483435/cole-assailly
Traceback (most recent call last):
  File "<ipython-input-6-ef681e2b523b>", line 59, in scrape
    scrape_player_page(link, csvwriter)
  File "<ipython-input-5-ea5904e59983>", line 88, in scrape_player_page
    position = player_page.find('div', text=position_text).next_element.next_element.next_element.text.strip()
AttributeError: 'NoneType' object has no attribute 'next_element'

**Comment by colinrsmall** [comment]
Fixed in 3f448be
